
(function(){
'use strict';
const APP_MODE=document.body.dataset.app||'coach';
const SHARED_KEY_PREFIX='coachSplitProject';
const STORAGE_KEYS={courses:`${SHARED_KEY_PREFIX}_courses`,workTimes:`${SHARED_KEY_PREFIX}_workTimes`,schedules:`${SHARED_KEY_PREFIX}_schedules`,courseDraft:`${APP_MODE}_courseDraft`,scheduleDraft:`${APP_MODE}_scheduleDraft`,workDraft:`${APP_MODE}_workDraft`,activePage:`${APP_MODE}_activePage`,userProducts:`${SHARED_KEY_PREFIX}_userProducts`,userBookings:`${SHARED_KEY_PREFIX}_userBookings`,userState:`${APP_MODE}_userState`,seed:`${SHARED_KEY_PREFIX}_seed`};
const WINDOW_STORE_PREFIX='__coach_split_projects_store__:';
const COURSE_FIELDS=['name','type','unit','limit','minutes','hours','price','buyLimit','giftHours','validDays','activeWay','advanceHour','giftDays','stores','intro'];
const SCHEDULE_FIELDS=['schCourse','schStart','schEnd','schStore','schLimit'];
const DEFAULT_COACH_NAME='王美丽';
const DEMO_SEED_VERSION='demo-v1';
let editingId=null,pendingAuditId=null,currentScheduleId=null,editingScheduleId=null,pickerTarget='';
let today=new Date();
let currentWeekStart=startOfWeek(today);
let selectedDate=new Date(today);
function emptyWorkTimes(){return {一:[],二:[],三:[],四:[],五:[],六:[],日:[]}}
let courses=load(STORAGE_KEYS.courses,[]);
let workTimes=load(STORAGE_KEYS.workTimes,emptyWorkTimes());
let schedules=load(STORAGE_KEYS.schedules,[]);
let userProducts=load(STORAGE_KEYS.userProducts,[]);
let userBookings=load(STORAGE_KEYS.userBookings,[]);
let currentUserProductId=null,currentUserBookingId=null,selectedUserScheduleId=null,selectedUserDate='';
function readWindowStore(){try{return window.name.startsWith(WINDOW_STORE_PREFIX)?JSON.parse(window.name.slice(WINDOW_STORE_PREFIX.length))||{}:{}}catch(e){return {}}}
function writeWindowStore(store){try{window.name=WINDOW_STORE_PREFIX+JSON.stringify(store)}catch(e){}}
function readRaw(key){try{const value=localStorage.getItem(key);if(value!==null)return value}catch(e){}try{const value=sessionStorage.getItem(key);if(value!==null)return value}catch(e){}const store=readWindowStore();return Object.prototype.hasOwnProperty.call(store,key)?store[key]:null}
function writeRaw(key,value){try{localStorage.setItem(key,value)}catch(e){}try{sessionStorage.setItem(key,value)}catch(e){}const store=readWindowStore();store[key]=value;writeWindowStore(store)}
function removeRaw(key){try{localStorage.removeItem(key)}catch(e){}try{sessionStorage.removeItem(key)}catch(e){}const store=readWindowStore();delete store[key];writeWindowStore(store)}
function load(key,fallback){const raw=readRaw(key);if(raw===null)return fallback;try{return JSON.parse(raw)??fallback}catch(e){return fallback}}
function saveAll(){writeRaw(STORAGE_KEYS.courses,JSON.stringify(courses));writeRaw(STORAGE_KEYS.workTimes,JSON.stringify(workTimes));writeRaw(STORAGE_KEYS.schedules,JSON.stringify(schedules));writeRaw(STORAGE_KEYS.userProducts,JSON.stringify(userProducts));writeRaw(STORAGE_KEYS.userBookings,JSON.stringify(userBookings));saveUserState()}
function saveUserState(){writeRaw(STORAGE_KEYS.userState,JSON.stringify({currentUserProductId,currentUserBookingId,selectedUserScheduleId,selectedUserDate}))}
function restoreUserState(){const state=load(STORAGE_KEYS.userState,{});currentUserProductId=state.currentUserProductId??null;currentUserBookingId=state.currentUserBookingId??null;selectedUserScheduleId=state.selectedUserScheduleId??null;selectedUserDate=state.selectedUserDate??''}
function buildDemoState(){const base=new Date();const makeDate=offset=>{const d=new Date(base);d.setDate(d.getDate()+offset);return fmtISO(d)};const todayDate=makeDate(0),nextDate=makeDate(1),thirdDate=makeDate(2);return{courses:[{id:1,name:'私教体验课',type:'一对一',unit:'按节',hours:6,minutes:60,price:299,validDays:30,stores:'振华商厦店',status:'已上架'},{id:2,name:'减脂塑形',type:'一对多',unit:'按时间',limit:2,hours:3,minutes:60,price:899,validDays:30,stores:'振华商厦店',status:'已上架'}],workTimes:{一:['09:00–12:00','14:00–18:00','18:30–21:30'],二:['09:00–12:00','14:00–18:00'],三:['09:00–12:00','14:00–18:00','18:30–21:30'],四:['09:00–12:00','14:00–18:00'],五:['09:00–12:00','14:00–18:00','18:30–21:30'],六:['09:00–12:00','14:00–18:00','18:30–21:30'],日:['09:00–12:00','14:00–18:00']},schedules:[{id:1001,courseId:1,courseType:'一对一',courseName:'私教体验课',date:todayDate,week:dayName(todayDate),start:'09:00',end:'10:00',store:'振华商厦店',limit:1,booked:0,status:'可预约',members:[]},{id:1002,courseId:1,courseType:'一对一',courseName:'私教体验课',date:todayDate,week:dayName(todayDate),start:'14:00',end:'15:00',store:'振华商厦店',limit:1,booked:0,status:'可预约',members:[]},{id:1003,courseId:1,courseType:'一对一',courseName:'私教体验课',date:nextDate,week:dayName(nextDate),start:'19:00',end:'20:00',store:'振华商厦店',limit:1,booked:0,status:'可预约',members:[]},{id:2001,courseId:2,courseType:'一对多',courseName:'减脂塑形小班',date:todayDate,week:dayName(todayDate),start:'10:00',end:'11:00',store:'振华商厦店',limit:2,booked:0,status:'可预约',members:[]},{id:2002,courseId:2,courseType:'一对多',courseName:'减脂塑形小班',date:todayDate,week:dayName(todayDate),start:'16:00',end:'17:00',store:'振华商厦店',limit:2,booked:1,status:'可预约',members:[{name:'张三',phone:'156****5666',time:'今天 10:20'}]},{id:2003,courseId:2,courseType:'一对多',courseName:'减脂塑形小班',date:thirdDate,week:dayName(thirdDate),start:'19:00',end:'20:00',store:'振华商厦店',limit:2,booked:0,status:'可预约',members:[]}],userProducts:[{id:'product-1',courseId:1,name:'私教体验课',type:'一对一',remain:6,remainVersion:'trial-6',coachName:DEFAULT_COACH_NAME,store:'振华商厦店'},{id:'product-2',courseId:2,name:'减脂塑形小班课',type:'一对多',remain:3,coachName:DEFAULT_COACH_NAME,store:'振华商厦店'}],userBookings:[],selectedUserDate:todayDate}}
function restoreDemoVersion(force=false){if(!force&&load(STORAGE_KEYS.seed,'')===DEMO_SEED_VERSION)return;const demo=buildDemoState();courses=demo.courses;workTimes=demo.workTimes;schedules=demo.schedules;userProducts=demo.userProducts;userBookings=demo.userBookings;editingId=null;pendingAuditId=null;currentScheduleId=null;editingScheduleId=null;currentUserProductId=null;currentUserBookingId=null;selectedUserScheduleId=null;selectedUserDate=demo.selectedUserDate;today=new Date();currentWeekStart=startOfWeek(today);selectedDate=new Date(today);clearCourseDraft();clearScheduleDraft();clearWorkDraft();saveActivePage('homePage');saveAll();writeRaw(STORAGE_KEYS.seed,JSON.stringify(DEMO_SEED_VERSION))}
function $(id){return document.getElementById(id)}
function val(id){return $(id).value}
function applyFieldValues(fields,data){if(!data)return;fields.forEach(id=>{const el=$(id);if(el&&data[id]!==undefined)el.value=data[id]})}
function bindDraftEvents(fields,handler){fields.forEach(id=>{const el=$(id);if(!el)return;el.addEventListener('input',handler);el.addEventListener('change',handler)})}
function saveCourseDraft(){writeRaw(STORAGE_KEYS.courseDraft,JSON.stringify(collectCourse()))}
function loadCourseDraft(){return load(STORAGE_KEYS.courseDraft,null)}
function clearCourseDraft(){removeRaw(STORAGE_KEYS.courseDraft)}
function collectScheduleDraft(){return{schCourse:val('schCourse'),schStart:val('schStart'),schEnd:val('schEnd'),schStore:val('schStore'),schLimit:val('schLimit')}}
function saveScheduleDraft(){writeRaw(STORAGE_KEYS.scheduleDraft,JSON.stringify(collectScheduleDraft()))}
function loadScheduleDraft(){return load(STORAGE_KEYS.scheduleDraft,null)}
function clearScheduleDraft(){removeRaw(STORAGE_KEYS.scheduleDraft)}
function defaultWorkLines(){return[{name:'上午',value:'09:00–12:00',off:false},{name:'下午',value:'14:00–18:00',off:false},{name:'晚上',value:'18:30–21:30',off:false}]}
function buildWorkDraftFromSaved(){const selected=Object.keys(workTimes).filter(day=>workTimes[day]&&workTimes[day].length);const baseDay=selected[0];const lines=(baseDay?workTimes[baseDay]:[]).map(value=>({name:'新增',value,off:false}));return{days:selected,lines:lines.length?lines:defaultWorkLines()}}
function collectWorkDraft(){return{days:[...document.querySelectorAll('#editDays .day.on')].map(x=>x.dataset.day),lines:[...document.querySelectorAll('#timeLines .time-line')].map(row=>({name:row.querySelector('.time-name').innerText.trim(),value:row.querySelector('.time-input').value.trim(),off:row.querySelector('.switch').classList.contains('off')}))}}
function saveWorkDraft(){if(!$('workEditPage'))return;writeRaw(STORAGE_KEYS.workDraft,JSON.stringify(collectWorkDraft()))}
function loadWorkDraft(){return load(STORAGE_KEYS.workDraft,null)}
function clearWorkDraft(){removeRaw(STORAGE_KEYS.workDraft)}
function saveActivePage(id){writeRaw(STORAGE_KEYS.activePage,JSON.stringify(id))}
function loadActivePage(){return load(STORAGE_KEYS.activePage,'homePage')}
function toast(msg){const t=$('toast');t.innerText=msg;t.style.display='block';setTimeout(()=>t.style.display='none',1500)}
function startOfWeek(d){const x=new Date(d);const day=x.getDay()||7;x.setHours(0,0,0,0);x.setDate(x.getDate()-day+1);return x}
function fmtMD(d){return `${d.getMonth()+1}月${d.getDate()}日`}
function fmtISO(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function timeToMin(t){const [h,m]=String(t||'00:00').split(':').map(Number);return h*60+(m||0)}
function addOneHour(t){const [h,m]=String(t||'10:00').split(':').map(Number);return `${String(Math.min(22,h+1)).padStart(2,'0')}:${String(m||0).padStart(2,'0')}`}
function dayName(dateStr){return ['日','一','二','三','四','五','六'][new Date(dateStr+'T00:00:00').getDay()]}
function getDateKey(dateInput){return typeof dateInput==='string'?dateInput:fmtISO(dateInput)}
function getWorkRangesForDate(dateInput){return workTimes[dayName(getDateKey(dateInput))]||[]}
function hasWorkTimeForDate(dateInput){return getWorkRangesForDate(dateInput).length>0}
function fmtUserDate(dateStr){const d=new Date(dateStr+'T00:00:00');return `${String(d.getMonth()+1).padStart(2,'0')}月${String(d.getDate()).padStart(2,'0')}日`}
function fmtUserDateTime(dateStr,start,end){return `${fmtUserDate(dateStr)} 星期${dayName(dateStr)} ${start}–${end}`}
function userSlotPeriod(start){const hour=parseInt(String(start).split(':')[0],10);return hour<12?'上午':hour<18?'下午':'晚上'}
function normalizeUserCourseName(course){if(!course)return'';if(course.type==='一对多'&&!/小班|团课|小组/.test(course.name))return `${course.name}小班课`;return course.name}
window.showPage=function(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');saveActivePage(id);if(id==='listPage')renderList();if(id==='workPage')renderWorkList();if(id==='calendarPage')renderCalendar();if(id==='userCoursePage')renderUserCourseList();if(id==='userBookingPage')renderUserBookingPage();if(id==='userSuccessPage')renderUserSuccessPage();if(id==='userBookingsPage')renderUserBookings()}
function getCoachStudentCount(){const keys=new Set();schedules.forEach(schedule=>{(schedule.members||[]).forEach(member=>{if(member.status==='已取消')return;const key=(member.phone||member.name||'').trim();if(key)keys.add(key)})});return keys.size}
function coachTodayTagClass(schedule){if(schedule.status==='停止预约')return'locked';if(Number(schedule.booked||0)>=Number(schedule.limit||1))return'full';return'pending'}
function coachTodayTagText(schedule){if(schedule.status==='停止预约')return'不可预约';if(Number(schedule.booked||0)>=Number(schedule.limit||1))return'已满';if(Number(schedule.booked||0)>0)return'部分已约';return'可预约'}
function meta(c){return c.unit==='按时间'?`${c.type} | ${c.hours||0}节 | ${c.limit||2}人 | ¥${c.price||0}/${c.validDays||30}天`:`${c.type} | ${c.hours||0}节 | ¥${c.price||0}/节`}
function renderList(){const kw=val('keyword').trim(),st=val('statusFilter'),box=$('courseList'),fab=document.querySelector('#listPage .fab');const list=courses.filter(c=>(!kw||c.name.includes(kw))&&(st==='全部'||c.status===st));fab.style.display=list.length?'flex':'none';if(!list.length){box.innerHTML='<div class="empty"><div class="empty-title">暂无课程</div><div>点击下方按钮创建课程，审核通过后可用于课程排班</div><div class="empty-action" onclick="openCreate()">新增课程</div></div>';return}box.innerHTML=list.map(c=>`<div class="course-card"><div class="course-main"><div class="course-name">${c.name}</div><div class="course-meta">${meta(c)}</div>${c.reason?`<div class="reason">驳回原因：${c.reason}</div>`:''}<div class="tag ${c.status==='待审核'?'pending':c.status==='已上架'?'online':c.status==='审核驳回'?'reject':'offline'}">${c.status}</div></div><div class="course-actions">${actions(c)}</div></div>`).join('')}
function actions(c){if(c.status==='待审核')return`<span onclick="editCourse(${c.id})">编辑</span><span onclick="withdraw(${c.id})">撤回</span>`;if(c.status==='已上架')return`<span onclick="editCourse(${c.id})">编辑</span><span onclick="offline(${c.id})">下架</span><span onclick="removeCourse(${c.id})">删除</span>`;if(c.status==='审核驳回')return`<span onclick="editCourse(${c.id})">编辑</span><span onclick="removeCourse(${c.id})">删除</span>`;return`<span onclick="editCourse(${c.id})">编辑</span><span onclick="online(${c.id})">上架</span><span onclick="removeCourse(${c.id})">删除</span>`}
window.openCreate=function(){editingId=null;$('formTitle').innerText='新增课程';document.querySelector('#formPage .bottom-btn').innerText='创建';COURSE_FIELDS.forEach(id=>$(id).value='');$('type').value='一对一';$('unit').value='按节';$('activeWay').value='';applyFieldValues(COURSE_FIELDS,loadCourseDraft());updateFormRows();showPage('formPage')}
window.editCourse=function(id){const c=courses.find(x=>x.id===id);if(!c)return;editingId=id;$('formTitle').innerText='新增课程';document.querySelector('#formPage .bottom-btn').innerText=c.status==='审核驳回'?'重新提交':'保存';['name','type','unit','limit','minutes','hours','price','buyLimit','giftHours','validDays','activeWay','advanceHour','giftDays','stores','intro'].forEach(k=>{const el=$(k);if(el)el.value=c[k]||''});updateFormRows();showPage('formPage')}
function collectCourse(){return{name:val('name')||'未命名课程',type:val('type'),unit:val('unit'),limit:val('limit'),minutes:val('minutes'),hours:val('hours'),price:val('price'),buyLimit:val('buyLimit'),giftHours:val('giftHours'),validDays:val('validDays'),activeWay:val('activeWay'),advanceHour:val('advanceHour'),giftDays:val('giftDays'),stores:val('stores'),intro:val('intro')}}
window.submitCourse=function(){const data=collectCourse();if(editingId){const idx=courses.findIndex(x=>x.id===editingId);const needAudit=courses[idx].status==='审核驳回'||courses[idx].status==='待审核';courses[idx]={...courses[idx],...data,reason:'',status:needAudit?'待审核':courses[idx].status};pendingAuditId=needAudit?courses[idx].id:null;toast(needAudit?'已提交审核':'已保存')}else{const newCourse={id:Date.now(),...data,status:'待审核'};courses.unshift(newCourse);pendingAuditId=newCourse.id;toast('创建成功，已进入待审核')}saveAll();clearCourseDraft();showPage('listPage');if(pendingAuditId)setTimeout(()=>$('auditMask').style.display='block',450)}
window.auditPass=function(){const c=courses.find(x=>x.id===pendingAuditId);if(c){c.status='已上架';c.reason=''}saveAll();$('auditMask').style.display='none';toast('审核通过，课程已上架');pendingAuditId=null;renderList()}
window.auditReject=function(){const c=courses.find(x=>x.id===pendingAuditId);if(c){c.status='审核驳回';c.reason='演示驳回：课程信息需补充'}saveAll();$('auditMask').style.display='none';toast('已驳回');pendingAuditId=null;renderList()}
window.withdraw=function(id){const c=courses.find(x=>x.id===id);if(c)c.status='已下架';saveAll();toast('已撤回');renderList()};window.offline=function(id){const c=courses.find(x=>x.id===id);if(c)c.status='已下架';saveAll();toast('已下架');renderList()};window.online=function(id){const c=courses.find(x=>x.id===id);if(c)c.status='待审核';saveAll();toast('已提交上架审核');renderList()};window.removeCourse=function(id){courses=courses.filter(x=>x.id!==id);saveAll();toast('已删除');renderList()}
function updateFormRows(){const type=val('type'),unit=val('unit');$('limitRow').style.display=type==='一对多'?'flex':'none';$('minuteRow').style.display=unit==='按节'?'flex':'none';$('giftHoursRow').style.display='flex';$('giftDaysRow').style.display=unit==='按时间'?'flex':'none'}
function renderWorkList(){const box=$('workList'),btn=$('workEditBtn');const has=Object.values(workTimes).some(v=>v.length);if(has){btn.style.display='flex';box.innerHTML=['一','二','三','四','五','六','日'].map(d=>`<div class="work-row"><div class="work-day">周${d}</div><div class="work-times">${workTimes[d].length?workTimes[d].join('&nbsp;&nbsp;&nbsp;'):'休息'}</div></div>`).join('')}else{btn.style.display='none';box.innerHTML='<div class="empty"><div class="empty-title">暂无工作时间</div><div>先设置可排课时间范围，后续新增课次时按该时间进行排班</div><div class="empty-action" onclick="openWorkEdit()">设置工作时间</div></div>'}}
window.openWorkEdit=function(){showPage('workEditPage');const draft=loadWorkDraft()||buildWorkDraftFromSaved();$('editDays').innerHTML=['一','二','三','四','五','六','日'].map(d=>`<div class="day${draft.days.includes(d)?' on':''}" data-day="${d}" onclick="toggleWorkDay(this)">${d}</div>`).join('');renderTimeLines(draft.lines)}
function renderTimeLines(lines=defaultWorkLines()){$('timeLines').innerHTML=lines.map(x=>`<div class="time-line"><div class="time-name">${x.name}</div><input class="time-input" value="${x.value}"><div class="switch${x.off?' off':''}" onclick="toggleWorkSwitch(this)"></div></div>`).join('')}
window.toggleWorkDay=function(el){el.classList.toggle('on');saveWorkDraft()}
window.toggleWorkSwitch=function(el){el.classList.toggle('off');saveWorkDraft()}
window.addTimeLine=function(){$('timeLines').insertAdjacentHTML('beforeend',`<div class="time-line"><div class="time-name">新增</div><input class="time-input" value="22:00–23:00"><div class="switch" onclick="toggleWorkSwitch(this)"></div></div>`);saveWorkDraft()}
window.saveWorkTime=function(){const selected=[...document.querySelectorAll('#editDays .day.on')].map(x=>x.dataset.day);const times=[...document.querySelectorAll('#timeLines .time-line')].filter(row=>!row.querySelector('.switch').classList.contains('off')).map(row=>row.querySelector('.time-input').value.trim()).filter(Boolean);['一','二','三','四','五','六','日'].forEach(d=>{workTimes[d]=selected.includes(d)?[...times]:[]});saveAll();clearWorkDraft();toast('工作时间已保存');showPage('workPage')}
function renderCalendarHeader(){const end=new Date(currentWeekStart);end.setDate(end.getDate()+6);$('rangeText').innerText=`${fmtMD(currentWeekStart)}–${fmtMD(end)}`;let html='';for(let i=0;i<7;i++){const d=new Date(currentWeekStart);d.setDate(d.getDate()+i);const isActive=fmtISO(d)===fmtISO(selectedDate);html+=`<div onclick="selectDate('${fmtISO(d)}')"><span class="${isActive?'active-date':''}">${d.getDate()}</span></div>`}$('datebar').innerHTML=html}
window.changeWeek=function(step){currentWeekStart.setDate(currentWeekStart.getDate()+step*7);selectedDate=new Date(currentWeekStart);renderCalendar()}
window.goToday=function(){today=new Date();selectedDate=new Date(today);currentWeekStart=startOfWeek(today);renderCalendar()}
window.selectDate=function(d){selectedDate=new Date(d+'T00:00:00');renderCalendar()}
function getLessonTone(s){if(s.status==='停止预约')return'gray';return Number(s.booked||0)>=Number(s.limit||1)?'purple':Number(s.booked||0)>0?'blue':'green'}
const CALENDAR_START_HOUR=9;
const CALENDAR_END_HOUR=22;
const CALENDAR_HOUR_HEIGHT=48;
function calendarStartMin(){return CALENDAR_START_HOUR*60}
function calendarEndMin(){return CALENDAR_END_HOUR*60}
function calendarTrackHeight(){return (CALENDAR_END_HOUR-CALENDAR_START_HOUR)*CALENDAR_HOUR_HEIGHT}
function buildCalendarLabels(){const labels=[];for(let hour=CALENDAR_START_HOUR;hour<=CALENDAR_END_HOUR;hour++)labels.push(`${String(hour).padStart(2,'0')}:00`);return labels}
function lessonMetrics(s){const minStart=calendarStartMin(),minEnd=calendarEndMin(),pxPerMin=CALENDAR_HOUR_HEIGHT/60;const startMin=Math.max(minStart,timeToMin(s.start));const endMin=Math.min(minEnd,timeToMin(s.end));const top=(startMin-minStart)*pxPerMin;const height=Math.max(20,(endMin-startMin)*pxPerMin-2);return{top,height,duration:endMin-startMin}}
function lessonStateText(s){if(s.status==='停止预约')return'不可预约';if(Number(s.booked||0)>=Number(s.limit||1))return`已满 ${s.booked}/${s.limit}`;if(Number(s.booked||0)>0)return`已约 ${s.booked}/${s.limit}`;return`${s.booked}/${s.limit}`}
function renderCalendar(){renderCalendarHeader();const grid=$('calendarGrid'),fab=document.querySelector('#calendarPage .fab');const daySchedules=schedules.filter(s=>(s.date||fmtISO(selectedDate))===fmtISO(selectedDate)&&s.status!=='已取消').sort((a,b)=>timeToMin(a.start)-timeToMin(b.start));if(!daySchedules.length){fab.style.display='none';grid.innerHTML='<div class="calendar-empty" style="grid-column:1/3"><div class="empty-title">暂无排课</div><div>当前日期暂无课次</div><div>请先创建并上架课程，再新增排课</div><div class="empty-action" onclick="openScheduleCreate()">新增排课</div></div>';return}fab.style.display='flex';const labels=buildCalendarLabels();const trackHeight=calendarTrackHeight();const timeHtml=`<div class="time-col" style="height:${trackHeight}px">${labels.map(label=>`<div class="time-label" style="top:${(timeToMin(label)-calendarStartMin())*(CALENDAR_HOUR_HEIGHT/60)}px">${label}</div>`).join('')}</div>`;const trackHtml=`<div class="calendar-track" style="height:${trackHeight}px">${daySchedules.map(s=>lessonHtml(s)).join('')}</div>`;grid.innerHTML=timeHtml+trackHtml}
function lessonHtml(s){const {top,height,duration}=lessonMetrics(s);const color=getLessonTone(s);const compact=duration<=30?' compact':'';return`<div class="lesson ${color}${compact}" style="top:${top}px;height:${height}px" onclick="openOp(${s.id})"><div class="lesson-line"><strong>${s.courseName}</strong><span class="lesson-meta">${s.start}–${s.end}</span><span class="lesson-meta">${lessonStateText(s)}</span></div></div>`}
function showScheduleTip(){const dateStr=fmtISO(selectedDate);$('scheduleTipText').innerHTML=`${fmtMD(selectedDate)}（周${dayName(dateStr)}）还没有设置工作时间，请先去配置后再新增排课。`;$('scheduleTipMask').style.display='block'}
window.closeScheduleTip=function(){$('scheduleTipMask').style.display='none'}
window.goSetWorkTime=function(){closeScheduleTip();openWorkEdit()}
window.openScheduleCreate=function(scheduleId=null){if(scheduleId===null&&!hasWorkTimeForDate(selectedDate)){showScheduleTip();return}editingScheduleId=scheduleId;const sel=$('schCourse'),online=courses.filter(c=>c.status==='已上架');sel.innerHTML=online.map(c=>`<option value="${c.id}">${c.name}${c.type==='一对多'?'小班':''}</option>`).join('')||'<option value="">暂无已上架课程</option>';$('scheduleFormTitle').innerText=scheduleId?'编辑课次':'新增课次';document.querySelector('#scheduleFormPage .orange-btn').innerText=scheduleId?'保存修改':'保存';if(scheduleId){const s=schedules.find(x=>x.id===scheduleId);const matched=online.find(c=>s.courseName.includes(c.name));if(matched)sel.value=matched.id;$('schStart').value=`${s.date}T${s.start}`;$('schEnd').value=`${s.date}T${s.end}`;$('schStore').value=s.store||'';$('schLimit').value=s.limit||''}else{SCHEDULE_FIELDS.forEach(id=>$(id).value='');const draft=loadScheduleDraft();if(draft){if([...sel.options].some(option=>option.value===draft.schCourse))sel.value=draft.schCourse;applyFieldValues(SCHEDULE_FIELDS,draft)}if(!val('schStore')||!val('schLimit'))fillScheduleCourseInfo()}showPage('scheduleFormPage')}
window.openDateTimePicker=function(target){pickerTarget=target;const dateSel=$('pickerDate'),timeSel=$('pickerTime');let dateHtml='';for(let i=0;i<7;i++){const d=new Date(currentWeekStart);d.setDate(d.getDate()+i);dateHtml+=`<option value="${fmtISO(d)}" ${fmtISO(d)===fmtISO(selectedDate)?'selected':''}>${fmtMD(d)}</option>`}dateSel.innerHTML=dateHtml;let timeHtml='';for(let h=9;h<=22;h++){['00','30'].forEach(m=>{if(h===22&&m==='30')return;const t=`${String(h).padStart(2,'0')}:${m}`;timeHtml+=`<option value="${t}">${t}</option>`})}timeSel.innerHTML=timeHtml;if($(target).value){dateSel.value=$(target).value.slice(0,10);timeSel.value=$(target).value.slice(11,16)}else{timeSel.value=target==='schEnd'&&val('schStart')?addOneHour(val('schStart').slice(11,16)):'10:00'}$('pickerMask').style.display='block'}
window.closeDateTimePicker=function(){$('pickerMask').style.display='none'}
window.confirmDateTimePicker=function(){$(pickerTarget).value=$('pickerDate').value+'T'+$('pickerTime').value;$('pickerMask').style.display='none';saveScheduleDraft()}
function fillScheduleCourseInfo(){const c=courses.find(x=>x.id===+val('schCourse'));$('schStore').value=c?(c.stores||''):'';$('schLimit').value=c?(c.type==='一对多'?(c.limit||2):1):'';saveScheduleDraft()}
window.saveSchedule=function(){const c=courses.find(x=>x.id===+val('schCourse'));if(!c){toast('请先创建并审核通过课程');return}const startVal=val('schStart'),endVal=val('schEnd');if(!startVal||!endVal){toast('请选择开始和结束时间');return}const dateStr=startVal.slice(0,10),start=startVal.slice(11,16),endt=endVal.slice(11,16);if(timeToMin(endt)<=timeToMin(start)){toast('结束时间必须晚于开始时间');return}const ranges=getWorkRangesForDate(dateStr);const ok=ranges.some(r=>{const [s1,e1]=r.split('–');return start>=s1&&endt<=e1});if(!ok){toast('不在工作时间范围内');return}const payload={courseId:c.id,courseType:c.type,courseName:c.name+(c.type==='一对多'?'小班':''),date:dateStr,week:dayName(dateStr),start,end:endt,store:val('schStore')||c.stores||'未选择门店',limit:+val('schLimit')||(c.type==='一对多'?+c.limit||2:1)};if(editingScheduleId){const idx=schedules.findIndex(x=>x.id===editingScheduleId);if(idx>-1)schedules[idx]={...schedules[idx],...payload};toast('课次已修改')}else{schedules.push({id:Date.now(),...payload,booked:0,status:'可预约',members:[]});toast('课次已保存')}editingScheduleId=null;saveAll();clearScheduleDraft();selectedDate=new Date(dateStr+'T00:00:00');currentWeekStart=startOfWeek(selectedDate);showPage('calendarPage')}
window.openOp=function(id){currentScheduleId=id;const s=schedules.find(x=>x.id===id);if(s)$('toggleBookingBtn').innerText=s.status==='停止预约'?'开启预约':'停止预约';$('opMask').style.display='block'};window.hideOp=function(){$('opMask').style.display='none'}
function coachBookingWayText(member){return member.source==='user'?'学员约教练':'教练约学员'}
function coachBookingNote(member){if(member.status==='待教练处理取消')return'学员发起了开课 3 小时内取消申请，等待教练处理。';if(member.status==='待学员确认完课'&&member.completeConfirmExpireAt)return`学员需在 24 小时内确认完课，超时将自动完课。`;if(member.status==='未到场')return'教练未同意取消，课程按未到场处理并正常核销。';if(member.status==='已完课'&&member.completedAt)return`完课时间：${new Date(member.completedAt).toLocaleString('zh-CN',{hour12:false})}`;return''}
function coachBookingActions(member){if(member.status==='待教练处理取消')return`<button class="mini-btn" onclick="approveCancelByCoach('${member.bookingId}')">同意取消</button><button class="mini-btn secondary" onclick="markNoShow('${member.bookingId}')">记为未到场</button>`;if(member.status==='待上课')return`<button class="mini-btn" onclick="confirmClassStart('${member.bookingId}')">确认上课</button>`;if(member.status==='上课中'&&member.source==='user')return`<button class="mini-btn" onclick="finishBookingByCoach('${member.bookingId}')">确认完课</button>`;if(member.status==='上课中'&&member.source==='coach')return`<button class="mini-btn" onclick="requestFinishConfirm('${member.bookingId}')">发起完课确认</button>`;return''}
function renderScheduleMemberCard(member){const actions=coachBookingActions(member),note=coachBookingNote(member);return`<div class="student-block"><div class="student-head"><div class="avatar"></div><div class="student-main"><div class="student-name">${member.name}</div><div class="student-meta">${member.phone||'未留手机号'}<br/>预约方式：${coachBookingWayText(member)}<br/>预约时间：${member.time||'--'}</div></div><div class="student-status">${member.status}</div></div>${actions?`<div class="student-actions">${actions}</div>`:''}${note?`<div class="student-note">${note}</div>`:''}</div>`}
window.openDetail=function(id=currentScheduleId){currentScheduleId=id;hideOp();settleBookingTimeouts();const s=schedules.find(x=>x.id===id);if(!s)return;const members=ensureScheduleMembers(s);$('detailBox').innerHTML=`<div class="detail-card"><div class="detail-top"><div class="detail-title">${s.courseName}</div><div class="detail-status">${s.status}</div></div><div class="detail-line">${s.date} ${s.start}–${s.end}<br/>${s.store||''}<br/>上课人数限制&nbsp; ${s.limit}人<br/>已约&nbsp; ${s.booked}人<br/>状态&nbsp; ${s.status}</div></div><div class="student-card"><div class="student-title">预约学员</div>${members.length?members.map(renderScheduleMemberCard).join(''):'<div style="color:#888;margin-top:12px">暂无预约学员</div>'}</div><button class="orange-btn" style="width:calc(100% - 36px);margin-left:18px" onclick="showMemberPage()">代学员预约</button>`;showPage('scheduleDetailPage')}
window.approveCancelByCoach=function(bookingId){cancelBookingSeat(bookingId);toast('已同意取消');openDetail(currentScheduleId)}
window.markNoShow=function(bookingId){updateBookingRecord(bookingId,{status:'未到场',completedAt:new Date().toISOString()});toast('已记为未到场');openDetail(currentScheduleId)}
window.confirmClassStart=function(bookingId){updateBookingRecord(bookingId,{status:'上课中'});toast('已确认上课');openDetail(currentScheduleId)}
window.finishBookingByCoach=function(bookingId){updateBookingRecord(bookingId,{status:'已完课',completedAt:new Date().toISOString()});toast('已确认完课');openDetail(currentScheduleId)}
window.requestFinishConfirm=function(bookingId){updateBookingRecord(bookingId,{status:'待学员确认完课',completeConfirmExpireAt:new Date(Date.now()+24*60*60*1000).toISOString()});toast('已发起完课确认');openDetail(currentScheduleId)}
window.showMemberPage=function(){hideOp();showPage('memberPage');renderMembers()}
function renderMembers(){const s=schedules.find(x=>x.id===currentScheduleId);if(!s){$('memberRows').innerHTML='<div class="empty" style="padding-top:48px"><div class="empty-title">暂无课次信息</div><div>请返回后重新选择要操作的课次</div></div>';return}const currentProduct=getUserProduct(`product-${s.courseId}`);const currentRemain=currentProduct?Number(currentProduct.remain||0):0;const members=[['当前用户','188****0000',currentRemain>0?`剩余：${currentRemain}次`:'无可用课时',currentRemain>0?1:0],['李三','139****6666','剩余：3次',1],['王五','138****3321','剩余：2次',1],['赵敏','137****2208','剩余：1次',1],['孙超','136****1188','无可用课时',0]];$('memberRows').innerHTML=members.map(m=>`<div class="member-row${m[3]?'':' disabled'}" ${m[3]?`onclick="bookMember('${m[0]}','${m[1]}')"`:''}><div class="avatar"></div><div class="member-info"><b>${m[0]}</b><br/>${m[1]}</div><div class="remain ${m[3]?'':'bad'}">${m[2]}</div></div>`).join('')}
window.bookMember=function(name,phone='139****6666'){const s=schedules.find(x=>x.id===currentScheduleId);if(!s)return;ensureScheduleMembers(s);if(s.status==='停止预约'){toast('该课次已停止预约');return}if(s.booked>=s.limit){toast('该课次已满');return}if(s.members.some(m=>m.name===name&&m.status!=='已取消')){toast('该会员已预约本课次');return}const isCurrentUser=isCurrentUserProfile(name,phone);const product=getUserProduct(`product-${s.courseId}`);if(isCurrentUser&&(!product||Number(product.remain||0)<=0)){toast('当前用户课时不足');return}const booking={bookingId:makeBookingId(),name,phone,time:'教练端预约',status:'待上课',source:'coach',isCurrentUser,createdAt:new Date().toISOString(),cancelRequestedAt:'',completeConfirmExpireAt:'',completedAt:''};s.members.push(booking);if(isCurrentUser&&product)product.remain=Math.max(0,Number(product.remain||0)-1);upsertUserBookingMirror(s,booking);syncScheduleBookedCount(s);saveAll();toast('代约成功');openDetail(s.id)}
window.editSchedule=function(){hideOp();openScheduleCreate(currentScheduleId)}
function refreshStopPage(){const s=schedules.find(x=>x.id===currentScheduleId);if(!s)return;const reopening=s.status==='停止预约';$('stopPageTitle').innerText=reopening?'开启预约':'停止预约';$('stopText').innerHTML=reopening?'开启预约后，学员将可以继续预约<br/>该课次未满员时会恢复可预约':'停止预约后，学员将无法再预约<br/>该课次已预约的学员不受影响';$('stopConfirmBtn').innerText=reopening?'确认开启':'确认停止';$('stopConfirmBtn').className=reopening?'orange-btn':'red-btn'}
window.showStopPage=function(){hideOp();refreshStopPage();showPage('stopPage')}
window.confirmStop=function(){const s=schedules.find(x=>x.id===currentScheduleId);if(!s)return;if(s.status==='停止预约'){s.status=Number(s.booked||0)>=Number(s.limit||1)?'已满':'可预约';toast('已开启预约')}else{s.status='停止预约';toast('已停止预约')}saveAll();showPage('calendarPage')}
window.cancelSchedule=function(){const s=schedules.find(x=>x.id===currentScheduleId);if(s){s.status='已取消';saveAll()}hideOp();toast('已取消课次');renderCalendar()}
window.deleteSchedule=function(){schedules=schedules.filter(x=>x.id!==currentScheduleId);saveAll();hideOp();toast('已删除课次');renderCalendar()}
function syncScheduleCourseData(){let changed=false;schedules.forEach(s=>{const course=courses.find(c=>String(s.courseId??'')===String(c.id)||(!s.courseId&&s.courseName&&s.courseName.includes(c.name)));if(!course)return;if(s.courseId!==course.id){s.courseId=course.id;changed=true}if(s.courseType!==course.type){s.courseType=course.type;changed=true}if(!s.store&&course.stores){s.store=course.stores;changed=true}});if(changed)saveAll()}
function syncUserProducts(){syncScheduleCourseData();const productMap=new Map(userProducts.map(p=>[String(p.courseId),p]));const sourceCourses=courses.filter(c=>c.status==='已上架'||schedules.some(s=>String(s.courseId??'')===String(c.id)));userProducts=sourceCourses.map(course=>{const existing=productMap.get(String(course.id))||{};const isTrial=/体验/.test(course.name);const defaultRemain=isTrial?6:Math.max(1,Number(course.hours)||1);const remain=isTrial?(existing.remainVersion==='trial-6'?existing.remain:6):(existing.remain??defaultRemain);return{id:existing.id||`product-${course.id}`,courseId:course.id,name:normalizeUserCourseName(course),type:course.type,remain,remainVersion:isTrial?'trial-6':existing.remainVersion,coachName:existing.coachName||DEFAULT_COACH_NAME,store:course.stores||existing.store||'振华商厦店'}}).sort((a,b)=>a.type===b.type?a.name.localeCompare(b.name,'zh-CN'):a.type==='一对一'?-1:1);saveAll()}
function getUserProduct(productId){return userProducts.find(p=>String(p.id)===String(productId))}
function getUserSlot(scheduleId){return schedules.find(s=>String(s.id)===String(scheduleId))}
function getUserRemainingSeats(slot){return Math.max(0,Number(slot.limit||1)-Number(slot.booked||0))}
function isCurrentUserProfile(name,phone=''){return name==='用户本人'||name==='当前用户'||phone==='188****0000'}
function bookingStartsAt(booking){return new Date(`${booking.date}T${booking.start}:00`)}
function hoursUntilBooking(booking){return (bookingStartsAt(booking).getTime()-Date.now())/36e5}
function makeBookingId(){return `booking-${Date.now()}-${Math.floor(Math.random()*1000)}`}
function upsertUserBookingMirror(schedule,member){if(!member.isCurrentUser)return;const booking={id:member.bookingId,productId:`product-${schedule.courseId}`,courseId:schedule.courseId,courseName:normalizeUserCourseName({name:schedule.courseName.replace(/小班$/,''),type:schedule.courseType}),coachName:DEFAULT_COACH_NAME,store:schedule.store,scheduleId:schedule.id,date:schedule.date,start:schedule.start,end:schedule.end,type:schedule.courseType,status:member.status,source:member.source||'user',customerName:member.name,customerPhone:member.phone,createdAt:member.createdAt||new Date().toISOString(),cancelRequestedAt:member.cancelRequestedAt||'',completeConfirmExpireAt:member.completeConfirmExpireAt||'',completedAt:member.completedAt||'',isCurrentUser:true};const idx=userBookings.findIndex(item=>String(item.id)===String(member.bookingId));if(idx>-1)userBookings[idx]={...userBookings[idx],...booking};else userBookings.unshift(booking)}
function syncScheduleBookedCount(schedule){schedule.booked=(schedule.members||[]).filter(member=>member.status!=='已取消').length;if(schedule.status!=='停止预约'&&schedule.status!=='已取消')schedule.status=schedule.booked>=Number(schedule.limit||1)?'已满':'可预约'}
function ensureScheduleMembers(schedule){let changed=false;if(!Array.isArray(schedule.members)){schedule.members=[];changed=true}schedule.members=schedule.members.map((member,index)=>{if(member.bookingId&&member.status&&member.source)return member;changed=true;return{bookingId:member.bookingId||`${schedule.id}-member-${index+1}`,name:member.name||'学员',phone:member.phone||'',time:member.time||'教练端预约',status:member.status||(member.confirmStatus==='已预约'?'待上课':'待上课'),source:member.source||(isCurrentUserProfile(member.name,member.phone)?'user':'coach'),isCurrentUser:member.isCurrentUser??isCurrentUserProfile(member.name,member.phone),createdAt:member.createdAt||new Date().toISOString(),cancelRequestedAt:member.cancelRequestedAt||'',completeConfirmExpireAt:member.completeConfirmExpireAt||'',completedAt:member.completedAt||''}});schedule.members.forEach(member=>upsertUserBookingMirror(schedule,member));syncScheduleBookedCount(schedule);if(changed)saveAll();return schedule.members}
function settleBookingTimeouts(){let changed=false;schedules.forEach(schedule=>{ensureScheduleMembers(schedule);schedule.members=schedule.members.map(member=>{if(member.status==='待学员确认完课'&&member.completeConfirmExpireAt&&new Date(member.completeConfirmExpireAt).getTime()<=Date.now()){changed=true;const next={...member,status:'已完课',completedAt:member.completeConfirmExpireAt||new Date().toISOString()};upsertUserBookingMirror(schedule,next);return next}return member});if(changed)syncScheduleBookedCount(schedule)});if(changed)saveAll()}
function migrateLegacyUserBookings(){let changed=false;userBookings=userBookings.map(booking=>{const next={...booking};if(next.status==='已预约'){next.status='待上课';changed=true}if(next.source===undefined){next.source='user';changed=true}if(next.isCurrentUser===undefined){next.isCurrentUser=true;changed=true}return next});if(changed)saveAll()}
function updateBookingRecord(bookingId,changes){let updated=null;schedules.forEach(schedule=>{ensureScheduleMembers(schedule);const idx=schedule.members.findIndex(member=>String(member.bookingId)===String(bookingId));if(idx>-1){schedule.members[idx]={...schedule.members[idx],...changes};updated=schedule.members[idx];upsertUserBookingMirror(schedule,schedule.members[idx]);syncScheduleBookedCount(schedule)}});const bookingIdx=userBookings.findIndex(item=>String(item.id)===String(bookingId));if(bookingIdx>-1)userBookings[bookingIdx]={...userBookings[bookingIdx],...changes};if(updated)saveAll();return updated}
function cancelBookingSeat(bookingId){let restored=null;schedules.forEach(schedule=>{ensureScheduleMembers(schedule);const idx=schedule.members.findIndex(member=>String(member.bookingId)===String(bookingId));if(idx>-1){schedule.members[idx]={...schedule.members[idx],status:'已取消',completedAt:new Date().toISOString()};restored=schedule.members[idx];upsertUserBookingMirror(schedule,schedule.members[idx]);syncScheduleBookedCount(schedule)}});const booking=userBookings.find(item=>String(item.id)===String(bookingId));if(booking){const product=getUserProduct(booking.productId);if(product)product.remain=Number(product.remain||0)+1;const idx=userBookings.findIndex(item=>String(item.id)===String(bookingId));if(idx>-1)userBookings[idx]={...userBookings[idx],status:'已取消',completedAt:new Date().toISOString()}}if(restored)saveAll();return restored}
function hasCurrentUserBookedSlot(scheduleId){return userBookings.some(booking=>String(booking.scheduleId)===String(scheduleId)&&!['已取消'].includes(booking.status))}
function getUserCourseSchedules(product){if(!product)return[];return schedules.filter(s=>String(s.courseId??'')===String(product.courseId)&&s.status!=='已取消').sort((a,b)=>`${a.date} ${a.start}`.localeCompare(`${b.date} ${b.start}`))}
function getUserAvailableDates(product){const todayStr=fmtISO(today);return [...new Set(getUserCourseSchedules(product).filter(s=>s.date>=todayStr).map(s=>s.date))].slice(0,7)}
function canUserBookSlot(slot,product){return!!slot&&!!product&&Number(product.remain||0)>0&&slot.status!=='停止预约'&&slot.status!=='已取消'&&getUserRemainingSeats(slot)>0}
function renderUserSlotButton(slot,product){const selected=String(selectedUserScheduleId)===String(slot.id),bookable=canUserBookSlot(slot,product),ownBooked=hasCurrentUserBookedSlot(slot.id),remainingSeats=getUserRemainingSeats(slot);let extra='';if(ownBooked)extra='<span class="user-slot-state">已约</span>';else if(slot.status==='停止预约')extra='<span class="user-slot-state">不可约</span>';else if(!bookable&&remainingSeats<=0)extra='<span class="user-slot-state">已约满</span>';else if(product.type==='一对多')extra=`<span class="user-slot-cap">余${remainingSeats}/${slot.limit}</span>`;return`<button class="user-slot${selected?' selected':''}${bookable?'':' disabled'}" ${bookable?`onclick="selectUserSlot(${slot.id})"`:'disabled'}>${slot.start}–${slot.end}${extra}</button>`}
function renderUserCourseList(){syncUserProducts();const box=$('userCourseList');if(!userProducts.length){box.innerHTML='<div class="user-empty"><div class="empty-title">暂无可预约课程</div><div>先在教练端创建并上架课程，再配置课次，用户端就会自动回填。</div></div>';return}box.innerHTML=userProducts.map(product=>`<div class="user-course-card"><div class="user-avatar"></div><div class="user-course-main"><div class="user-course-title">${product.name}</div><div class="user-course-sub">剩余${product.remain}课时</div></div><button class="user-action-btn" ${product.remain>0?`onclick="openUserBooking('${product.id}')"`:'disabled'}>${product.remain>0?'预约':'已用完'}</button></div>`).join('')}
window.openUserCourses=function(){syncUserProducts();saveUserState();showPage('userCoursePage')}
window.openUserBooking=function(productId){const keepSelection=String(currentUserProductId)===String(productId);currentUserProductId=productId;const product=getUserProduct(productId),dates=getUserAvailableDates(product);if(!dates.includes(selectedUserDate))selectedUserDate=dates[0]||'';if(!keepSelection)selectedUserScheduleId=null;saveUserState();showPage('userBookingPage')}
function renderUserBookingPage(){const product=getUserProduct(currentUserProductId),coachBox=$('userCoachCard'),dateBox=$('userDateStrip'),slotBox=$('userSlotGroups'),bookBtn=$('userBookBtn');if(!product){coachBox.innerHTML='';dateBox.innerHTML='';slotBox.innerHTML='<div class="user-empty">请选择课程后再预约</div>';bookBtn.disabled=true;bookBtn.innerText='请选择预约时段';return}const dates=getUserAvailableDates(product);coachBox.innerHTML=`<div class="user-brief-card"><div class="user-avatar"></div><div class="user-course-main"><div class="user-course-title">${product.coachName}</div><div class="user-store">${product.store}</div></div></div>`;if(!dates.length){selectedUserDate='';selectedUserScheduleId=null;dateBox.innerHTML='';slotBox.innerHTML='<div class="user-empty">当前课程暂无可预约时段</div>';bookBtn.disabled=true;bookBtn.innerText=Number(product.remain||0)>0?'暂无可预约时段':'剩余课时不足';saveUserState();return}if(!dates.includes(selectedUserDate))selectedUserDate=dates[0];dateBox.innerHTML=dates.map(dateStr=>`<div class="user-date-item${dateStr===selectedUserDate?' active':''}" onclick="selectUserDate('${dateStr}')"><div class="user-date-week">周${dayName(dateStr)}</div><div class="user-date-day">${fmtISO(today)===dateStr?'今':new Date(dateStr+'T00:00:00').getDate()}</div></div>`).join('');const daySlots=getUserCourseSchedules(product).filter(s=>s.date===selectedUserDate);const sections=['上午','下午','晚上'].map(period=>{const items=daySlots.filter(slot=>userSlotPeriod(slot.start)===period);if(!items.length)return'';return`<div class="user-slot-section"><div class="user-slot-label">${period}</div><div class="user-slot-grid">${items.map(slot=>renderUserSlotButton(slot,product)).join('')}</div></div>`}).join('');slotBox.innerHTML=sections||'<div class="user-empty">当日暂无可预约时段</div>';const selectedSlot=getUserSlot(selectedUserScheduleId);if(!canUserBookSlot(selectedSlot,product))selectedUserScheduleId=null;const finalSlot=getUserSlot(selectedUserScheduleId);bookBtn.disabled=!finalSlot;bookBtn.innerText=finalSlot?`预约${fmtUserDateTime(finalSlot.date,finalSlot.start,finalSlot.end)}`:Number(product.remain||0)>0?'请选择预约时段':'剩余课时不足';saveUserState()}
window.selectUserDate=function(dateStr){selectedUserDate=dateStr;selectedUserScheduleId=null;saveUserState();renderUserBookingPage()}
window.selectUserSlot=function(scheduleId){selectedUserScheduleId=scheduleId;saveUserState();renderUserBookingPage()}
window.openUserBookingConfirm=function(){const product=getUserProduct(currentUserProductId),slot=getUserSlot(selectedUserScheduleId);if(!canUserBookSlot(slot,product)){toast(Number(product?.remain||0)>0?'请选择可预约时段':'剩余课时不足');return}$('userConfirmText').innerHTML=`将预约${fmtUserDateTime(slot.date,slot.start,slot.end)}的训练，成功预约将使用1节${product.type==='一对多'?'小班':'私教'}课时`;$('userConfirmMask').style.display='block'}
window.hideUserConfirm=function(){$('userConfirmMask').style.display='none'}
window.confirmUserBooking=function(){const product=getUserProduct(currentUserProductId),slot=getUserSlot(selectedUserScheduleId);if(!canUserBookSlot(slot,product)){hideUserConfirm();renderUserBookingPage();toast('当前时段已不可预约');return}ensureScheduleMembers(slot);if(userBookings.some(booking=>String(booking.scheduleId)===String(slot.id)&&booking.status!=='已取消')){hideUserConfirm();toast('这个时段已经预约过了');return}product.remain=Math.max(0,Number(product.remain||0)-1);const booking={bookingId:makeBookingId(),name:'用户本人',phone:'188****0000',time:'用户端预约',status:'待上课',source:'user',isCurrentUser:true,createdAt:new Date().toISOString(),cancelRequestedAt:'',completeConfirmExpireAt:'',completedAt:''};slot.members.push(booking);upsertUserBookingMirror(slot,booking);syncScheduleBookedCount(slot);currentUserBookingId=booking.bookingId;saveAll();hideUserConfirm();showPage('userSuccessPage')}
function userBookingNote(booking){if(booking.status==='待上课'&&hoursUntilBooking(booking)<3)return'距开课不足 3 小时，需联系教练协商取消。';if(booking.status==='待教练处理取消')return'取消申请已提交，等待教练处理。';if(booking.status==='待学员确认完课')return'请在 24 小时内确认完课，超时系统会自动完课。';if(booking.status==='未到场')return'教练未同意取消，本次课程按未到场处理并正常核销。';if(booking.status==='已完课'&&booking.completedAt)return`完课时间：${new Date(booking.completedAt).toLocaleString('zh-CN',{hour12:false})}`;return''}
function userBookingActions(booking){if(booking.status==='待上课')return`<button class="mini-btn${hoursUntilBooking(booking)>=3?'':' secondary'}" onclick="handleUserCancel('${booking.id}')">${hoursUntilBooking(booking)>=3?'取消预约':'联系教练取消'}</button>`;if(booking.status==='待学员确认完课')return`<button class="mini-btn" onclick="confirmUserFinish('${booking.id}')">确认完课</button>`;return''}
window.handleUserCancel=function(bookingId){settleBookingTimeouts();const booking=userBookings.find(item=>String(item.id)===String(bookingId));if(!booking)return;if(hoursUntilBooking(booking)>=3){cancelBookingSeat(bookingId);toast('已取消预约')}else{updateBookingRecord(bookingId,{status:'待教练处理取消',cancelRequestedAt:new Date().toISOString()});toast('已提交取消申请，请联系教练处理')}renderUserBookings();if(currentScheduleId)openDetail(currentScheduleId)}
window.confirmUserFinish=function(bookingId){updateBookingRecord(bookingId,{status:'已完课',completedAt:new Date().toISOString()});toast('已确认完课');renderUserBookings();if(currentScheduleId)openDetail(currentScheduleId)}
function renderUserSuccessPage(){const booking=userBookings.find(item=>String(item.id)===String(currentUserBookingId));$('userSuccessSummary').innerHTML=booking?`<div>教练：${booking.coachName}</div><div>门店：${booking.store}</div><div>时段：${fmtUserDateTime(booking.date,booking.start,booking.end)}</div>`:'<div>暂无预约信息</div>'}
window.openUserBookings=function(){showPage('userBookingsPage')}
function renderUserBookings(){settleBookingTimeouts();const box=$('userBookingsList');if(!userBookings.length){box.innerHTML='<div class="user-empty"><div class="empty-title">暂无预约记录</div><div>完成预约后，会在这里展示你的课程安排。</div></div>';return}box.innerHTML=userBookings.map(booking=>`<div class="user-booking-card"><div class="user-booking-head"><div><div class="user-booking-name">${booking.courseName}</div><div class="user-store">${booking.coachName} · ${booking.store}</div></div><div class="user-status">${booking.status}</div></div><div class="user-booking-time">${fmtUserDateTime(booking.date,booking.start,booking.end)}</div>${userBookingActions(booking)?`<div class="user-booking-actions">${userBookingActions(booking)}</div>`:''}${userBookingNote(booking)?`<div class="user-booking-note">${userBookingNote(booking)}</div>`:''}</div>`).join('')}
function initFabDrag(){document.querySelectorAll('.fab').forEach(fab=>{let dragging=false,moved=false,ox=0,oy=0;const start=e=>{const p=e.touches?e.touches[0]:e,r=fab.getBoundingClientRect();dragging=true;moved=false;ox=p.clientX-r.left;oy=p.clientY-r.top;fab.style.left=r.left+'px';fab.style.top=r.top+'px';fab.style.right='auto';fab.style.bottom='auto'};const move=e=>{if(!dragging)return;const p=e.touches?e.touches[0]:e;fab.style.left=Math.max(8,Math.min(window.innerWidth-64,p.clientX-ox))+'px';fab.style.top=Math.max(70,Math.min(window.innerHeight-74,p.clientY-oy))+'px';moved=true;e.preventDefault()};const end=()=>{dragging=false;if(moved){fab.dataset.moved='1';setTimeout(()=>fab.dataset.moved='0',80)}};fab.addEventListener('click',e=>{if(fab.dataset.moved==='1'){e.stopImmediatePropagation();e.preventDefault()}},true);fab.addEventListener('mousedown',start);window.addEventListener('mousemove',move,{passive:false});window.addEventListener('mouseup',end);fab.addEventListener('touchstart',start,{passive:false});window.addEventListener('touchmove',move,{passive:false});window.addEventListener('touchend',end)})}
function runTests(){console.assert(typeof window.showPage==='function','showPage should be global');console.assert(timeToMin('10:30')===630,'timeToMin works');console.assert(fmtISO(new Date('2026-05-06T00:00:00'))==='2026-05-06','fmtISO works');console.assert(startOfWeek(new Date('2026-05-06T00:00:00')).getDay()===1,'startOfWeek should be Monday');console.assert(['一','二','三','四','五','六','日'].includes(dayName(fmtISO(new Date()))),'dayName works')}
function boot(){restoreDemoVersion();restoreUserState();migrateLegacyUserBookings();settleBookingTimeouts();$('type').addEventListener('change',updateFormRows);$('unit').addEventListener('change',updateFormRows);$('keyword').addEventListener('input',renderList);$('statusFilter').addEventListener('change',renderList);$('schCourse').addEventListener('change',fillScheduleCourseInfo);$('timeLines').addEventListener('input',saveWorkDraft);$('timeLines').addEventListener('change',saveWorkDraft);bindDraftEvents(COURSE_FIELDS,saveCourseDraft);bindDraftEvents(SCHEDULE_FIELDS,saveScheduleDraft);syncUserProducts();saveAll();initFabDrag();renderList();renderWorkList();renderCalendar();runTests();const activePage=loadActivePage();if(activePage==='formPage')openCreate();else if(activePage==='scheduleFormPage')openScheduleCreate();else if(activePage==='workEditPage')openWorkEdit();else if(activePage==='userCoursePage')openUserCourses();else if(activePage==='userBookingPage'&&currentUserProductId)openUserBooking(currentUserProductId);else if(activePage==='userBookingsPage')openUserBookings();else if(activePage==='userSuccessPage')showPage('userSuccessPage');else if($(activePage))showPage(activePage)}
function coachHomeTemplate(){return `<div class="coach-dashboard"><div class="coach-header-card"><div class="coach-header-top"><div id="coachAvatarText" class="coach-avatar-badge">王</div><div class="coach-header-main"><div id="coachGreeting" class="coach-greeting">下午好，王教练</div><div class="coach-location-row"><span class="coach-location-dot"></span><span id="coachStoreName">黄毛健身房</span></div></div></div></div><div id="coachStatGrid" class="coach-stat-grid"></div><div class="coach-panel"><div class="coach-panel-head"><div class="coach-panel-title">今日待办</div><div class="coach-panel-link" onclick="showPage('calendarPage')">查看全部</div></div><div id="coachTodoList"></div></div><div class="coach-panel"><div class="coach-panel-head"><div class="coach-panel-title">快捷功能</div></div><div class="coach-quick-grid"><div class="coach-quick-item" onclick="openCoachFeature('contract')"><div class="coach-quick-icon">签</div><div class="coach-quick-label">门店签约</div></div><div class="coach-quick-item" onclick="openCoachFeature('work')"><div class="coach-quick-icon">时</div><div class="coach-quick-label">工作时间</div></div><div class="coach-quick-item" onclick="openCoachFeature('course')"><div class="coach-quick-icon">课</div><div class="coach-quick-label">课程管理</div></div><div class="coach-quick-item" onclick="openCoachFeature('booking')"><div class="coach-quick-icon">约</div><div class="coach-quick-label">预约管理</div></div><div class="coach-quick-item" onclick="openCoachFeature('calendar')"><div class="coach-quick-icon">历</div><div class="coach-quick-label">排课日历</div></div><div class="coach-quick-item" onclick="openCoachFeature('student')"><div class="coach-quick-icon">员</div><div class="coach-quick-label">学员管理</div></div><div class="coach-quick-item" onclick="openCoachFeature('order')"><div class="coach-quick-icon">单</div><div class="coach-quick-label">私教订单</div></div></div></div><div class="coach-panel"><div class="coach-panel-head"><div class="coach-panel-title">今日课程</div><div class="coach-panel-link" onclick="showPage('calendarPage')">查看全部</div></div><div id="coachTodayCourseList"></div></div></div><div class="coach-bottom-nav"><div class="coach-bottom-item active" onclick="showPage('homePage')"><div class="coach-bottom-icon">首</div><div>首页</div></div><div class="coach-bottom-item" onclick="showPage('listPage')"><div class="coach-bottom-icon">课</div><div>课程</div></div><div class="coach-bottom-item" onclick="showPage('calendarPage')"><div class="coach-bottom-icon">排</div><div>排班</div></div><div class="coach-bottom-item" onclick="openCoachFeature('mine')"><div class="coach-bottom-icon">我</div><div>我的</div></div></div>`}
function renderCoachHomeLayout(){const page=$('homePage');if(page&&page.dataset.layoutReady!=='1'){page.innerHTML=coachHomeTemplate();page.dataset.layoutReady='1'}}
function getCoachStoreName(){const scheduleStore=schedules.find(item=>item.store&&item.status!=='已取消')?.store;const courseStore=courses.find(item=>item.stores)?.stores;return scheduleStore||courseStore||'黄毛健身房'}
function getCoachGreetingText(){const hour=new Date().getHours();if(hour<12)return'上午好';if(hour<18)return'下午好';return'晚上好'}
function getScheduleActiveMembers(schedule){return ensureScheduleMembers(schedule).filter(member=>member.status!=='已取消')}
function getCoachTodaySchedules(){const todayKey=fmtISO(today);return schedules.filter(schedule=>schedule.date===todayKey&&schedule.status!=='已取消'&&getScheduleActiveMembers(schedule).length>0).sort((a,b)=>timeToMin(a.start)-timeToMin(b.start))}
function getCoachMonthSchedules(){const monthKey=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}`;return schedules.filter(schedule=>String(schedule.date||'').startsWith(monthKey)&&schedule.status!=='已取消'&&getScheduleActiveMembers(schedule).length>0)}
function getCoachEarliestTime(list){return list.length?list[0].start:'--:--'}
function coachStatusView(schedule){const members=getScheduleActiveMembers(schedule);if(members.some(member=>member.status==='上课中'))return{text:'上课中',tone:'active'};if(members.some(member=>member.status==='待学员确认完课'))return{text:'待确认',tone:'review'};if(members.every(member=>['已完课','未到场'].includes(member.status)))return{text:'已完成',tone:'done'};if(members.some(member=>member.status==='待上课'))return{text:'待上课',tone:'pending'};return{text:'已预约',tone:'pending'}}
function coachCourseMetaText(schedule){const members=getScheduleActiveMembers(schedule);const names=members.map(member=>member.name).filter(Boolean);const memberText=schedule.courseType==='一对多'?`${names.slice(0,2).join('、')}${names.length>2?`等${names.length}人`:names.length?'':'多人课程'}`:(names[0]||'待分配学员');return `${memberText} · ${schedule.store||'未设置门店'}`}
function getCoachHomeStats(){const todaySchedules=getCoachTodaySchedules();const monthSchedules=getCoachMonthSchedules();return[{icon:'今',label:'今日课程',value:todaySchedules.length,unit:'节',note:todaySchedules.length?`最早 ${getCoachEarliestTime(todaySchedules)} 开始`:'今日暂无课程'},{icon:'月',label:'本月课程',value:monthSchedules.length,unit:'节',note:`本月已安排 ${monthSchedules.length} 节`},{icon:'员',label:'学员总数',value:getCoachStudentCount(),unit:'人',note:'按已预约学员去重统计'}]}
function getCoachTodoItems(){const items=[];getCoachTodaySchedules().forEach(schedule=>{getScheduleActiveMembers(schedule).forEach(member=>{if(member.status==='待上课'){items.push({scheduleId:schedule.id,bookingId:member.bookingId,time:schedule.start,courseName:schedule.courseName,memberName:member.name,statusText:'待上课',tone:'pending',action:'start',buttonText:'开始上课'})}else if(member.status==='上课中'&&member.source==='user'){items.push({scheduleId:schedule.id,bookingId:member.bookingId,time:schedule.start,courseName:schedule.courseName,memberName:member.name,statusText:'待完课',tone:'review',action:'finish',buttonText:'确认完课'})}})});return items.sort((a,b)=>timeToMin(a.time)-timeToMin(b.time))}
function renderCoachStatCards(){const box=$('coachStatGrid');if(!box)return;box.innerHTML=getCoachHomeStats().map(item=>`<div class="coach-stat-box"><div class="coach-stat-icon">${item.icon}</div><div class="coach-stat-name">${item.label}</div><div class="coach-stat-number">${item.value}<small>${item.unit}</small></div><div class="coach-stat-note">${item.note}</div></div>`).join('')}
function renderCoachTodoList(){const box=$('coachTodoList');if(!box)return;const items=getCoachTodoItems();if(!items.length){box.innerHTML='<div class="coach-empty-state">今天暂时没有需要处理的课程，当前状态都已经同步好了。</div>';return}box.innerHTML=`<div class="coach-todo-list">${items.map(item=>`<div class="coach-todo-item"><div class="coach-todo-time">${item.time}</div><div class="coach-todo-main" onclick="openCoachScheduleDetail(${item.scheduleId})"><div class="coach-todo-top"><div class="coach-todo-name">${item.courseName}</div><span class="coach-chip ${item.tone}">${item.statusText}</span></div><div class="coach-todo-meta">${item.memberName} · ${fmtISO(today)} 星期${dayName(fmtISO(today))}</div></div><button class="coach-todo-btn" onclick="handleCoachTodoAction(${item.scheduleId},'${item.bookingId}','${item.action}')">${item.buttonText}</button></div>`).join('')}</div>`}
function renderCoachTodayCourseList(){const box=$('coachTodayCourseList');if(!box)return;const items=getCoachTodaySchedules();if(!items.length){box.innerHTML='<div class="coach-empty-state">今天还没有已预约的课程，新的预约会自动回填到这里。</div>';return}box.innerHTML=`<div class="coach-course-list">${items.map(schedule=>{const status=coachStatusView(schedule);return`<div class="coach-course-item" onclick="openCoachScheduleDetail(${schedule.id})"><div class="coach-course-row"><div><div class="coach-course-name">${schedule.courseName}</div><div class="coach-course-meta">${coachCourseMetaText(schedule)}<br/>${fmtMD(new Date(schedule.date+'T00:00:00'))} 星期${dayName(schedule.date)} ${schedule.start}-${schedule.end}</div></div><span class="coach-chip ${status.tone}">${status.text}</span></div></div>`}).join('')}</div>`}
function renderCoachHome(){renderCoachHomeLayout();const avatar=DEFAULT_COACH_NAME.slice(0,1)||'教';if($('coachAvatarText'))$('coachAvatarText').innerText=avatar;if($('coachGreeting'))$('coachGreeting').innerText=`${getCoachGreetingText()}，${DEFAULT_COACH_NAME}`;if($('coachStoreName'))$('coachStoreName').innerText=getCoachStoreName();renderCoachStatCards();renderCoachTodoList();renderCoachTodayCourseList()}
function showCoachPage(id){document.querySelectorAll('.page').forEach(page=>page.classList.remove('active'));$(id).classList.add('active');saveActivePage(id);if(id==='homePage')renderCoachHome();if(id==='listPage')renderList();if(id==='workPage')renderWorkList();if(id==='calendarPage')renderCalendar();if(id==='userCoursePage')renderUserCourseList();if(id==='userBookingPage')renderUserBookingPage();if(id==='userSuccessPage')renderUserSuccessPage();if(id==='userBookingsPage')renderUserBookings()}
window.showPage=showPage=showCoachPage
window.openCoachFeature=function(feature){if(feature==='work'){showCoachPage('workPage');return}if(feature==='course'){showCoachPage('listPage');return}if(feature==='calendar'){showCoachPage('calendarPage');return}toast('该功能正在建设中')}
window.openCoachScheduleDetail=function(scheduleId){currentScheduleId=scheduleId;openDetail(scheduleId)}
window.handleCoachTodoAction=function(scheduleId,bookingId,action){currentScheduleId=scheduleId;if(action==='start'){updateBookingRecord(bookingId,{status:'上课中'});toast('已开始上课')}else{updateBookingRecord(bookingId,{status:'已完课',completedAt:new Date().toISOString()});toast('已确认完课')}renderCoachHome()}
function coachIcon(name){
  const common='viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"';
  const icons={
    coach:`<svg ${common}><circle cx="12" cy="8" r="3.4"/><path d="M6.5 19c1.2-3.1 3.4-4.7 5.5-4.7 2.1 0 4.3 1.6 5.5 4.7"/><path d="M4 5.5c1.4-1.8 3.2-2.7 5.3-2.7M20 5.5c-1.4-1.8-3.2-2.7-5.3-2.7"/></svg>`,
    pin:`<svg ${common}><path d="M12 20s-5.5-4.8-5.5-9.3A5.5 5.5 0 0 1 17.5 10.7C17.5 15.2 12 20 12 20Z"/><circle cx="12" cy="10.2" r="1.7"/></svg>`,
    calendarCheck:`<svg ${common}><rect x="3.5" y="5" width="17" height="15" rx="3"/><path d="M7.5 3.5v3M16.5 3.5v3M3.5 9.5h17"/><path d="m8.5 14 2 2 5-5"/></svg>`,
    chart:`<svg ${common}><path d="M4.5 18.5h15"/><path d="M6.5 15.5 10 12l3 2.5 4.5-6"/><path d="M16 8.5h2.5V11"/></svg>`,
    users:`<svg ${common}><circle cx="9" cy="9" r="3"/><path d="M3.8 18c.8-2.7 2.8-4.2 5.2-4.2 2.4 0 4.4 1.5 5.2 4.2"/><path d="M16.5 8.2a2.3 2.3 0 1 1 0 4.6"/><path d="M18.8 18c-.3-1.4-1.1-2.6-2.3-3.4"/></svg>`,
    contract:`<svg ${common}><path d="M8 3.5h6l4 4v13h-10a3.5 3.5 0 0 1-3.5-3.5V7A3.5 3.5 0 0 1 8 3.5Z"/><path d="M14 3.5V8h4"/><path d="m8.5 15.5 2.2-2.2 2 2 2.8-2.8"/></svg>`,
    clock:`<svg ${common}><circle cx="12" cy="12" r="8.5"/><path d="M12 7.5v5l3 2"/></svg>`,
    course:`<svg ${common}><rect x="4" y="5" width="16" height="14" rx="3"/><path d="m10 9 5 3-5 3Z"/></svg>`,
    booking:`<svg ${common}><rect x="4" y="4.5" width="16" height="15" rx="3"/><path d="M8 3v3M16 3v3M4 9h16"/><path d="M9 13h6M9 16h4"/></svg>`,
    schedule:`<svg ${common}><rect x="4" y="5" width="16" height="15" rx="3"/><path d="M8 3.5v3M16 3.5v3M4 9.5h16"/><path d="M8 13h3M13 13h3M8 16.5h3"/></svg>`,
    student:`<svg ${common}><circle cx="12" cy="8.5" r="3.2"/><path d="M5.5 19c1-3.1 3.5-4.8 6.5-4.8s5.5 1.7 6.5 4.8"/></svg>`,
    order:`<svg ${common}><path d="M7 3.5h10v17l-3-1.8-2 1.8-2-1.8-3 1.8Z"/><path d="M9 8.5h6M9 12h6M9 15.5h4"/></svg>`,
    home:`<svg ${common}><path d="M4.5 10.5 12 4l7.5 6.5"/><path d="M6.5 9.5v10h11v-10"/></svg>`,
    mine:`<svg ${common}><circle cx="12" cy="8" r="3.2"/><path d="M5.5 19c1-3.1 3.5-4.8 6.5-4.8s5.5 1.7 6.5 4.8"/></svg>`
  };
  return icons[name]||icons.course;
}
function coachQuickFeatures(){
  return[
    {key:'contract',label:'门店签约',icon:'contract'},
    {key:'work',label:'工作时间',icon:'clock'},
    {key:'course',label:'课程管理',icon:'course'},
    {key:'booking',label:'预约管理',icon:'booking'},
    {key:'calendar',label:'排课日历',icon:'schedule'},
    {key:'student',label:'学员管理',icon:'student'},
    {key:'order',label:'私教订单',icon:'order'}
  ];
}
function coachHomeTemplate(){
  return `<div class="coach-dashboard">
    <div class="coach-header-card">
      <div class="coach-header-top">
        <div class="coach-avatar-badge">${coachIcon('coach')}</div>
        <div class="coach-header-main">
          <div class="coach-header-kicker">Coach workspace</div>
          <div id="coachGreeting" class="coach-greeting">下午好，王教练</div>
          <div class="coach-location-row">
            <div class="coach-store-pill">${coachIcon('pin')}<span id="coachStoreName">黄毛健身房</span></div>
          </div>
        </div>
        <div class="coach-header-action" onclick="showPage('calendarPage')">${coachIcon('calendarCheck')}</div>
      </div>
    </div>
    <div id="coachStatGrid" class="coach-stat-grid"></div>
    <div class="coach-panel">
      <div class="coach-panel-head">
        <div class="coach-panel-title">今日待办</div>
        <div class="coach-panel-link" onclick="showPage('calendarPage')">查看全部</div>
      </div>
      <div id="coachTodoList"></div>
    </div>
    <div class="coach-panel">
      <div class="coach-panel-head">
        <div class="coach-panel-title">快捷功能</div>
      </div>
      <div class="coach-quick-grid">${coachQuickFeatures().map(item=>`<div class="coach-quick-item" onclick="openCoachFeature('${item.key}')"><div class="coach-quick-icon">${coachIcon(item.icon)}</div><div class="coach-quick-label">${item.label}</div></div>`).join('')}</div>
    </div>
    <div class="coach-panel">
      <div class="coach-panel-head">
        <div class="coach-panel-title">今日课程</div>
        <div class="coach-panel-link" onclick="showPage('calendarPage')">查看全部</div>
      </div>
      <div id="coachTodayCourseList"></div>
    </div>
  </div>
  <div class="coach-bottom-nav">
    <div class="coach-bottom-item active" onclick="showPage('homePage')"><div class="coach-bottom-icon">${coachIcon('home')}</div><div>首页</div></div>
    <div class="coach-bottom-item" onclick="showPage('listPage')"><div class="coach-bottom-icon">${coachIcon('course')}</div><div>课程</div></div>
    <div class="coach-bottom-item" onclick="showPage('calendarPage')"><div class="coach-bottom-icon">${coachIcon('schedule')}</div><div>排班</div></div>
    <div class="coach-bottom-item" onclick="openCoachFeature('mine')"><div class="coach-bottom-icon">${coachIcon('mine')}</div><div>我的</div></div>
  </div>`;
}
function renderCoachHomeLayout(){const page=$('homePage');if(page&&page.dataset.layoutReady!=='coach-v2'){page.innerHTML=coachHomeTemplate();page.dataset.layoutReady='coach-v2'}}
function getCoachStoreName(){const scheduleStore=schedules.find(item=>item.store&&item.status!=='已取消')?.store;const courseStore=courses.find(item=>item.stores)?.stores;return scheduleStore||courseStore||'黄毛健身房'}
function getCoachGreetingText(){const hour=new Date().getHours();if(hour<12)return'上午好';if(hour<18)return'下午好';return'晚上好'}
function getScheduleActiveMembers(schedule){return ensureScheduleMembers(schedule).filter(member=>member.status!=='已取消')}
function getCoachTodaySchedules(){const todayKey=fmtISO(today);return schedules.filter(schedule=>schedule.date===todayKey&&schedule.status!=='已取消'&&getScheduleActiveMembers(schedule).length>0).sort((a,b)=>timeToMin(a.start)-timeToMin(b.start))}
function getCoachMonthSchedules(){const monthKey=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}`;return schedules.filter(schedule=>String(schedule.date||'').startsWith(monthKey)&&schedule.status!=='已取消'&&getScheduleActiveMembers(schedule).length>0)}
function getCoachEarliestTime(list){return list.length?list[0].start:'--:--'}
function coachStatusView(schedule){const members=getScheduleActiveMembers(schedule);if(members.some(member=>member.status==='上课中'))return{text:'上课中',tone:'active'};if(members.some(member=>member.status==='待学员确认完课'))return{text:'待确认',tone:'review'};if(members.every(member=>['已完课','未到场'].includes(member.status)))return{text:'已完成',tone:'done'};if(members.some(member=>member.status==='待上课'))return{text:'待上课',tone:'pending'};return{text:'已预约',tone:'pending'}}
function coachCourseMetaText(schedule){const members=getScheduleActiveMembers(schedule);const names=members.map(member=>member.name).filter(Boolean);const memberText=schedule.courseType==='一对多'?`${names.slice(0,2).join('、')}${names.length>2?`等${names.length}人`:names.length?'':'多人课程'}`:(names[0]||'待分配学员');return `${memberText} · ${schedule.store||'未设置门店'}`}
function getCoachHomeStats(){const todaySchedules=getCoachTodaySchedules();const monthSchedules=getCoachMonthSchedules();return[{icon:'calendarCheck',label:'今日课程',value:todaySchedules.length,unit:'节',note:todaySchedules.length?`最早 ${getCoachEarliestTime(todaySchedules)} 开始`:'今日暂无课程'},{icon:'chart',label:'本月课程',value:monthSchedules.length,unit:'节',note:`本月已安排 ${monthSchedules.length} 节`},{icon:'users',label:'学员总数',value:getCoachStudentCount(),unit:'人',note:'按已预约学员去重统计'}]}
function getCoachTodoItems(){const items=[];getCoachTodaySchedules().forEach(schedule=>{getScheduleActiveMembers(schedule).forEach(member=>{if(member.status==='待上课'){items.push({scheduleId:schedule.id,bookingId:member.bookingId,time:schedule.start,courseName:schedule.courseName,memberName:member.name,statusText:'待上课',tone:'pending',action:'start',buttonText:'开始上课'})}else if(member.status==='上课中'&&member.source==='user'){items.push({scheduleId:schedule.id,bookingId:member.bookingId,time:schedule.start,courseName:schedule.courseName,memberName:member.name,statusText:'待完课',tone:'review',action:'finish',buttonText:'确认完课'})}})});return items.sort((a,b)=>timeToMin(a.time)-timeToMin(b.time))}
function renderCoachStatCards(){const box=$('coachStatGrid');if(!box)return;box.innerHTML=getCoachHomeStats().map(item=>`<div class="coach-stat-box"><div class="coach-stat-icon">${coachIcon(item.icon)}</div><div class="coach-stat-name">${item.label}</div><div class="coach-stat-number">${item.value}<small>${item.unit}</small></div><div class="coach-stat-note">${item.note}</div></div>`).join('')}
function renderCoachTodoList(){const box=$('coachTodoList');if(!box)return;const items=getCoachTodoItems();if(!items.length){box.innerHTML='<div class="coach-empty-state">今天暂时没有需要处理的课程，当前状态都已经同步好了。</div>';return}box.innerHTML=`<div class="coach-todo-list">${items.map(item=>`<div class="coach-todo-item"><div class="coach-todo-time">${item.time}</div><div class="coach-todo-main" onclick="openCoachScheduleDetail(${item.scheduleId})"><div class="coach-todo-top"><div class="coach-todo-name">${item.courseName}</div><span class="coach-chip ${item.tone}">${item.statusText}</span></div><div class="coach-todo-meta">${item.memberName} · ${fmtISO(today)} 星期${dayName(fmtISO(today))}</div></div><button class="coach-todo-btn" onclick="handleCoachTodoAction(${item.scheduleId},'${item.bookingId}','${item.action}')">${item.buttonText}</button></div>`).join('')}</div>`}
function renderCoachTodayCourseList(){const box=$('coachTodayCourseList');if(!box)return;const items=getCoachTodaySchedules();if(!items.length){box.innerHTML='<div class="coach-empty-state">今天还没有已预约的课程，新的预约会自动回填到这里。</div>';return}box.innerHTML=`<div class="coach-course-list">${items.map(schedule=>{const status=coachStatusView(schedule);return`<div class="coach-course-item" onclick="openCoachScheduleDetail(${schedule.id})"><div class="coach-course-row"><div><div class="coach-course-name">${schedule.courseName}</div><div class="coach-course-meta">${coachCourseMetaText(schedule)}<br/>${fmtMD(new Date(schedule.date+'T00:00:00'))} 星期${dayName(schedule.date)} ${schedule.start}-${schedule.end}</div></div><span class="coach-chip ${status.tone}">${status.text}</span></div></div>`}).join('')}</div>`}
function renderCoachHome(){renderCoachHomeLayout();if($('coachGreeting'))$('coachGreeting').innerText=`${getCoachGreetingText()}，${DEFAULT_COACH_NAME}`;if($('coachStoreName'))$('coachStoreName').innerText=getCoachStoreName();renderCoachStatCards();renderCoachTodoList();renderCoachTodayCourseList()}
function showCoachPage(id){document.querySelectorAll('.page').forEach(page=>page.classList.remove('active'));$(id).classList.add('active');saveActivePage(id);if(id==='homePage')renderCoachHome();if(id==='listPage')renderList();if(id==='workPage')renderWorkList();if(id==='calendarPage')renderCalendar();if(id==='userCoursePage')renderUserCourseList();if(id==='userBookingPage')renderUserBookingPage();if(id==='userSuccessPage')renderUserSuccessPage();if(id==='userBookingsPage')renderUserBookings()}
window.showPage=showPage=showCoachPage
window.openCoachFeature=function(feature){if(feature==='work'){showCoachPage('workPage');return}if(feature==='course'){showCoachPage('listPage');return}if(feature==='calendar'){showCoachPage('calendarPage');return}toast('该功能正在建设中')}
window.openCoachScheduleDetail=function(scheduleId){currentScheduleId=scheduleId;openDetail(scheduleId)}
window.handleCoachTodoAction=function(scheduleId,bookingId,action){currentScheduleId=scheduleId;if(action==='start'){updateBookingRecord(bookingId,{status:'上课中'});toast('已开始上课')}else{updateBookingRecord(bookingId,{status:'已完课',completedAt:new Date().toISOString()});toast('已确认完课')}renderCoachHome()}
function getCoachStatusTime(){const now=new Date();return `${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`}
function coachHomeTemplate(){
  return `<div class="coach-dashboard">
    <div class="coach-header-card">
      <div class="coach-header-top">
        <div class="coach-avatar-badge">${coachIcon('coach')}</div>
        <div class="coach-header-main">
          <div id="coachGreeting" class="coach-greeting">下午好，张教练👋</div>
          <div class="coach-location-row">
            <div class="coach-store-pill">${coachIcon('pin')}<span id="coachStoreName">黄毛健身房</span><span class="coach-store-arrow">›</span></div>
          </div>
        </div>
      </div>
    </div>
    <div id="coachStatGrid" class="coach-stat-grid"></div>
    <div class="coach-panel">
      <div class="coach-panel-head">
        <div class="coach-panel-title">今日待办</div>
        <div class="coach-panel-link" onclick="showPage('calendarPage')">查看全部</div>
      </div>
      <div id="coachTodoList"></div>
    </div>
    <div class="coach-panel">
      <div class="coach-panel-head">
        <div class="coach-panel-title">快捷功能</div>
      </div>
      <div class="coach-quick-grid">${coachQuickFeatures().map(item=>`<div class="coach-quick-item" onclick="openCoachFeature('${item.key}')"><div class="coach-quick-icon">${coachIcon(item.icon)}</div><div class="coach-quick-label">${item.label}</div></div>`).join('')}</div>
    </div>
    <div class="coach-panel">
      <div class="coach-panel-head">
        <div class="coach-panel-title">今日课程</div>
        <div class="coach-panel-link" onclick="showPage('calendarPage')">查看全部</div>
      </div>
      <div id="coachTodayCourseList"></div>
    </div>
  </div>
  <div class="coach-bottom-nav">
    <div class="coach-bottom-item active" onclick="showPage('homePage')"><div class="coach-bottom-icon">${coachIcon('home')}</div><div>首页</div></div>
    <div class="coach-bottom-item" onclick="showPage('listPage')"><div class="coach-bottom-icon">${coachIcon('course')}</div><div>课程</div></div>
    <div class="coach-bottom-item" onclick="showPage('calendarPage')"><div class="coach-bottom-icon">${coachIcon('schedule')}</div><div>排班</div></div>
    <div class="coach-bottom-item" onclick="openCoachFeature('mine')"><div class="coach-bottom-icon">${coachIcon('mine')}</div><div>我的</div></div>
  </div>`;
}
function getCoachHomeStats(){
  const todaySchedules=getCoachTodaySchedules();
  const monthSchedules=getCoachMonthSchedules();
  const monthDelta=Math.max(1,Math.min(3,monthSchedules.length||1));
  const newStudentDelta=Math.max(1,Math.min(2,getCoachStudentCount()||1));
  return[
    {icon:'calendarCheck',label:'今日课程',value:todaySchedules.length,unit:'节',noteHtml:todaySchedules.length?`最早 ${getCoachEarliestTime(todaySchedules)} 开始`:'今日暂无课程'},
    {icon:'chart',label:'本月课程',value:monthSchedules.length,unit:'节',noteHtml:`较上月 <span class="coach-stat-up">↑ ${monthDelta}</span>`},
    {icon:'users',label:'学员总数',value:getCoachStudentCount(),unit:'人',noteHtml:`本月新增 <span class="coach-stat-up">↑ ${newStudentDelta}</span>`}
  ];
}
function renderCoachStatCards(){const box=$('coachStatGrid');if(!box)return;box.innerHTML=getCoachHomeStats().map(item=>`<div class="coach-stat-box"><div class="coach-stat-title"><div class="coach-stat-icon">${coachIcon(item.icon)}</div><div class="coach-stat-name">${item.label}</div></div><div class="coach-stat-number">${item.value}<small>${item.unit}</small></div><div class="coach-stat-note">${item.noteHtml}</div></div>`).join('')}
function renderCoachHome(){renderCoachHomeLayout();if($('coachGreeting'))$('coachGreeting').innerText=`${getCoachGreetingText()}，${DEFAULT_COACH_NAME}👋`;if($('coachStoreName'))$('coachStoreName').innerText=getCoachStoreName();renderCoachStatCards();renderCoachTodoList();renderCoachTodayCourseList()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
